import {
  createMemoryHistory,
  createRouter as _createRouter,
  createWebHistory
} from 'vue-router';

// Import routes generated by vite-plugin-pages
// https://github.com/hannoeru/vite-plugin-pages
import routes from '~pages';

// Export the router-creating function
export function createRouter() {
  return _createRouter({
    // Use appropriate history implementation for server/client
    // import.meta.env.SSR is injected by Vite.
    history: import.meta.env.SSR ? createMemoryHistory() : createWebHistory(),
    routes
  });
};